# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

pool: TestPool
  #vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureDeployConn'
    subscriptionId: '9245ca19-7afc-427d-b9fa-aad41676a94d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'Australia East'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/matthewboler/AzureDeploy/master/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName mb20210319a'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
