trigger:
- master

pool: TestPool

steps:
- task: AzureFileCopy@4
  inputs:
    SourcePath: 'CreateWebApp'
    azureSubscription: 'AzureDeployConn'
    Destination: 'AzureBlob'
    storage: 'mb20210319a4pg7nidrkd6fm'
    ContainerName: 'projecttemplates'
  name: AzureFileCopy