trigger:
- master

pool: TestPool

  variables: 
    - group: UAT

steps:
- script: echo $(parameterFileName) # uses macro syntax

- task: AzureFileCopy@4
  inputs:
    SourcePath: 'CreateWebApp'
    azureSubscription: 'AzureDeployConn'
    Destination: 'AzureBlob'
    storage: 'mb20210319a4pg7nidrkd6fm'
    ContainerName: 'projecttemplates'
  name: AzureFileCopy

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureDeployConn'
    subscriptionId: '9245ca19-7afc-427d-b9fa-aad41676a94d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'Australia East'
    templateLocation: 'URL of the file'
    csmFileLink: '$(AzureFileCopy.StorageContainerUri)CreateWebApp/azuredeploy2step.json$(AzureFileCopy.StorageContainerSasToken)'
    overrideParameters: -storageName $(AzureFileCopy.StorageContainerUri) -storageSAS $(AzureFileCopy.StorageContainerSasToken)
    deploymentMode: 'Incremental'
    deploymentName: 'deploy1'
  name: AzureResourceDeployment